[package]
name = "extractsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
sql-parse = "0.20.0"

tree-sitter = "0.20.8"
tree-sitter-sql = { git = "https://github.com/nokome/tree-sitter-sql", rev = "6afc167f6ac120727fbc3e0d721e168414f15795" }
